dataset: 'arabic' # ['arabic', 'google-speech-command']
root_dir: 'F:/Datasets/keyword-spotting/abdulkaderghandoura-arabic-speech-commands-dataset-72f3438/dataset'
out_dir: './combine_data'
df_path: './output/stage1/data.csv'
info_path: './output/stage1/info.json'
n_samples: 10
ratio_split: 0.5  # the number of speakers
words: ['previous', 'previous']
mode: 'duplicate'