dataset: 'audio_mnist' # ['arabic', 'google-speech-command']
root_dir: './data/audio_mnist'
out_dir: './data-stage2/audio_mnist/4-4-4'
df_path: './process_data/audio_mnist/0.5/data.csv'
info_path: './process_data/audio_mnist/0.5/info.json'
n_samples: 50
ratio_split: 0.5  # the number of speakers
words: ['4','4','4']