Dataset:
  root_dir: './data'
  noise_path: ''
  rir_path: '../dataset/rir_data/RIRS_NOISES/simulated_rirs'
  musan_path: '../dataset/musan_data/musan'

Pairs:
  Female:
    eval_list: './data/loop1/3/female_development.txt'
  Male:
    eval_list: './data/loop1/3/male_development.txt'

AudioProcessing:
  # Init
  sample_rate: 16000
  duration: 1 # second
  add_sample: 240 #
  # Sample = sr * duration + add_sample

Parameters:
  lr: &lr 0.0001
  lr_decay: 0.97
  num_workers: 0
  max_epoch: 70
  batch_size: 128
  scheduler: 'StepLR' # CyclicLR, StepLR, ReduceLROnPlateau
  base_lr:  0.00000001
  max_lr: *lr 
  lr_scheduler_patience: 1
  lr_scheduler_gamma: 0.05

  # For TDNN
  C: 1024
  m: 0.2
  s: 30
  test_step: 1
  device: 'cuda:2'

RunningFolder:
  run_path: 'checkpoint_stage2/loop1/3'
  score_file: 'score-stage.txt'
  threshold_file: 'threshold-tuning.txt'


