Dataset:
  root_dir: 'data/audio_mnist/'
  noise_path: ''
  rir_path: './data/RIRS_NOISES/simulated_rirs'
  musan_path: './data/musan_data/musan'


AudioProcessing:
  # Init
  sample_rate: 16000
  duration: 1 # second
  add_sample: 240 #
  # Sample = sr * duration + add_sample

Parameters:
  lr: &lr 0.0001
  lr_decay: 0.97
  num_workers: 0
  max_epoch: 35
  batch_size: 64
  scheduler: 'StepLR' # CyclicLR, StepLR, ReduceLROnPlateau
  base_lr:  0.00000001
  max_lr: *lr 
  lr_scheduler_patience: 1
  lr_scheduler_gamma: 0.05

  # For TDNN
  C: 1024
  m: 0.2
  s: 30
  test_step: 1
  device: 'cuda:0'

RunningFolder:
  run_path: 'checkpoints_stage1/audio_mnist/stage1/female2/exp3'
  score_file: 'score-stage.txt'
