Dataset:
  root_dir: &root_dir 'data'
  noise_test_paths: [ '../dataset/speech_commands_v0.01/_background_noise_'] #'../dataset/arabic/background_noise',
  rir_path: '../dataset/rir_data/RIRS_NOISES/simulated_rirs'
  musan_path: '../dataset/musan_data/musan'
  path: &path '/loop4/9_9_9_9'

RunningFolder:
  run_path: &run_path !join ['checkpoints_combine', *path]
  score_file: 'score-stage.txt'
  threshold_file: 'threshold-tuning.txt'

Pairs:
  threshold_path : !join [*run_path,'/thresholds.json']
  Female:
    dev_list: !join [*root_dir,*path, '/female_development.txt']
    eval_list: !join [*root_dir,*path, '/female_evaluation.txt']
  Male:
    dev_list: !join [*root_dir,*path, '/male_development.txt']
    eval_list: !join [*root_dir,*path,'/male_evaluation.txt']

AudioProcessing:
  # Init
  sample_rate: 16000
  duration: 4 # second
  add_sample: 240 #
  # Sample = sr * duration + add_sample

Parameters:
  lr: &lr 0.0001
  lr_decay: 0.97
  num_workers: 0
  max_epoch: 50
  batch_size: 64
  scheduler: 'StepLR' # CyclicLR, StepLR, ReduceLROnPlateau
  base_lr:  0.00000001
  max_lr: *lr 
  lr_scheduler_patience: 1
  lr_scheduler_gamma: 0.05

  # For TDNN
  C: 1024
  m: 0.2
  s: 30
  test_step: 1
  device: 'cuda:0'


